language: csharp

before_install:
  - sudo add-apt-repository --yes ppa:avsm/ppa
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
  - sudo apt-get install libssl-dev opam libsqlite3-dev g++-5 gcc-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 200
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 200
  - export OPAMYES=true
  - opam init
  - eval $(opam config env)
  - opam switch 4.02.3
  - eval $(opam config env)
  - opam install batteries sqlite3 fileutils stdint
  - export Z3=z3-4.4.1-x64-ubuntu-14.04
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/$Z3.zip
  - unzip $Z3.zip
  - export PATH=/home/travis/build/FStarLang/FStar/$Z3/bin:/home/travis/build/FStarLang/FStar/bin:$PATH
  - ocamlopt -config
  - ocamlfind ocamlopt -config

script:
  - make -C src
  - make -C src ocaml
  - make -C src/ocaml-output
  - make -C contrib/CoreCrypto/ml
  - make -C contrib/CoreCrypto/ml test
  - make -C examples/unit-tests
  - make -C src regressions OTHERFLAGS=--lax

notifications:
  slack: everestexpedition:NqWwcvMIxouVIbC5IhF0loqX

git:
    depth: 3
