language: csharp

matrix:
  include:
    - env: Ubuntu=14.04
      os: linux
      dist: trusty
      sudo: required
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.2
      rvm: system
    # - env: OSX=10.10
    #   os: osx
    #   osx_image: xcode7.1
    #   rvm: system

before_install:
  - ./ci/before_install.sh

install:
  - ./ci/install.sh

script:
  - ./ci/script.sh

notifications:
  slack: everestexpedition:NqWwcvMIxouVIbC5IhF0loqX

git:
    depth: 3
