language: csharp

matrix:
  include:
    - env: Ubuntu=14.04
      os: linux
      dist: trusty
      sudo: required
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.2
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7.1
      rvm: system

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:avsm/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:0k53d-karl-f830m/openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc ocaml opam z3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes libssl-dev opam libsqlite3-dev g++-5 gcc-5; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 200; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 200; fi
  - export OPAMYES=true
  - opam init
  - eval $(opam config env)
  - opam switch 4.02.3
  - eval $(opam config env)
  - opam install batteries sqlite3 fileutils stdint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export Z3=z3-4.4.1-x64-ubuntu-14.04; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/$Z3.zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unzip $Z3.zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/home/travis/build/FStarLang/FStar/$Z3/bin:/home/travis/build/FStarLang/FStar/bin:$PATH; fi
  - ocamlfind ocamlopt -config

script:
  - echo -e "\e[31m=== Some info about the environment ===\e[0m"
  - ocamlfind ocamlopt -config
  - free -h
  - echo -e "\e[31m=== Bootstrap cycle ===\e[0m"
  - make -C src
  - make -C src ocaml
  - make -C src/ocaml-output
  - echo -e "\e[31m=== Running tests ===\e[0m"
  - make -C examples/unit-tests
  - make -C src regressions OTHERFLAGS=--lax

notifications:
  slack: everestexpedition:NqWwcvMIxouVIbC5IhF0loqX

git:
    depth: 3
