language: csharp

before_install:
  - sudo add-apt-repository --yes ppa:avsm/ppa
  - sudo apt-get -qq update
  - sudo apt-get install libssl-dev opam libsqlite3-dev

script:
  - make -C src
  - make -C src ocaml
  - export OPAMYES=true
  - opam init
  - eval $(opam config env)
  - opam install batteries sqlite3 fileutils stdint
  - make -C src/ocaml-output
  - export PATH=$(realpath bin):$PATH
  - make -C contrib/CoreCrypto/ml
  - make -C contrib/CoreCrypto/ml test
  - make -C examples/unit-tests
  - make -C src regressions OTHERFLAGS=--lax

install: true

notifications:
  slack: everestexpedition:NqWwcvMIxouVIbC5IhF0loqX

git:
    depth: 1
